### ISSUE TITLE
wiki里面的cheeger constant定义和这里面的cheeger constant定义不太一样

### ISSUE THREAD

**Issue by yguooo** [yatyricky/LevelDesign#1]
wiki里面的定义是找到一个|\partial A|/|A|的minimum，而这里面的cheeger constant似乎是一个基于expectation的定义，而且对于不同的order也适用。想问一下这两个定义之间有没有什么联系，比如某种equivalence。或者有没有关于本文中cheeger constant的其他reference？多谢 

（好奇的黑魂玩家 ）

**Comment by yatyricky** [comment]
这里定义的是 https://zhuanlan.zhihu.com/p/415025159 里面4.2的定义，原文是中文，我乱翻的，因此和wiki不一样，抱歉。
